name: stephykroon
favicon: null
layout_spectrum: 0.41916833259165287
typography_spectrum: 0.418673895066604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4857343374751508
  lightness: 0.9164348845370114
  saturation: 0.017184684984385967
  rhythmicContrast: 0.21119152731262147
purpose: []
